# Generated by Django 3.0.4 on 2021-04-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_load_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetyperesource',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='exercisetyperesource',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
        migrations.DeleteModel(
            name='ExerciseTypeResource',
        ),
    ]
