# Generated by Django 4.2.11 on 2024-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_load_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiConceptOntology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, max_length=255, null=True)),
                ('ontology', models.ManyToManyField(blank=True, to='ontology.ontology')),
            ],
        ),
    ]
