# Generated by Django 3.0.4 on 2021-03-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=40)),
                ('visible', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=250)),
                ('library', models.CharField(choices=[('EXOSET', 'Exoset'), ('EXTERNAL', 'External')], default='EXOSET', max_length=8)),
                ('language', models.CharField(choices=[('FRANÇAIS', 'Français'), ('ITALIANO', 'Italiano'), ('ENGLISH', 'English')], default='FRANÇAIS', max_length=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('document_type', models.CharField(choices=[('STATEMENT', 'Statement'), ('SOLUTION', 'Solution'), ('APPENDIX', 'Appendix'), ('EXTRA', 'Extra')], max_length=9)),
                ('language', models.CharField(blank=True, choices=[('FRANÇAIS', 'Français'), ('ITALIANO', 'Italiano'), ('ENGLISH', 'English')], max_length=8, null=True)),
                ('file', models.FileField(upload_to='document/%Y/%m/%d/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Resource')),
            ],
        ),
    ]
