# Generated by Django 3.0.4 on 2021-04-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exoset.document.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=250)),
                ('library', models.CharField(choices=[('EXOSET', 'Exoset'), ('EXTERNAL', 'External')], default='EXOSET', max_length=8)),
                ('language', models.CharField(choices=[('FRANÇAIS', 'Français'), ('ITALIANO', 'Italiano'), ('ENGLISH', 'English')], default='FRANÇAIS', max_length=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FilePathField(allow_files=False, allow_folders=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github')),
                ('style', models.FilePathField(allow_folders=True, blank=True, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('document_type', models.CharField(choices=[('STATEMENT', 'Statement'), ('SOLUTION', 'Solution'), ('APPENDIX', 'Appendix'), ('EXTRA', 'Extra')], max_length=9)),
                ('language', models.CharField(blank=True, choices=[('FRANÇAIS', 'Français'), ('ITALIANO', 'Italiano'), ('ENGLISH', 'English')], max_length=8, null=True)),
                ('file', models.FileField(storage=exoset.document.models.OverwriteStorage(), upload_to=exoset.document.models.update_filename)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Resource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resourcesourcefile',
            constraint=models.UniqueConstraint(fields=('source', 'style'), name='different_source_style'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(document_type='STATEMENT'), fields=('document_type', 'resource'), name='unique_statement_resource'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(document_type='SOLUTION'), fields=('document_type', 'resource'), name='unique_solution_resource'),
        ),
    ]
