# Generated by Django 3.0.12 on 2021-08-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='source',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=255, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github'),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='style',
            field=models.FilePathField(allow_folders=True, blank=True, max_length=255, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github'),
        ),
    ]
