# Generated by Django 3.0.12 on 2021-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210803_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='source',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=255, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github/template_exoset'),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='style',
            field=models.FilePathField(allow_folders=True, blank=True, max_length=255, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github/template_exoset'),
        ),
    ]
