# Generated by Django 3.0.12 on 2021-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210906_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='flag',
            field=models.CharField(blank=True, choices=[('REVISEMD', 'Revise metadata'), ('REVISEFILE', 'Revise files'), ('OBSOLETE', 'Obsolete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='source',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=255, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github/exoset'),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='style',
            field=models.FilePathField(allow_folders=True, blank=True, max_length=255, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github/exoset'),
        ),
    ]
