# Generated by Django 3.0.4 on 2021-03-16 09:59

from django.db import migrations, models
import exoset.document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210308_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=exoset.document.models.OverwriteStorage(), upload_to=exoset.document.models.update_filename),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(document_type='STATEMENT'), fields=('document_type', 'resource'), name='unique_statement_resource'),
        ),
    ]
