# Generated by Django 3.0.4 on 2021-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20210316_0959'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(document_type='SOLUTION'), fields=('document_type', 'resource'), name='unique_solution_resource'),
        ),
    ]
