# Generated by Django 3.0.12 on 2022-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20210922_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, choices=[('FRANÇAIS', 'Français'), ('ENGLISH', 'English')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(choices=[('FRANÇAIS', 'Français'), ('ENGLISH', 'English')], default='FRANÇAIS', max_length=8),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='source',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=255, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github/ExosetProd'),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='style',
            field=models.FilePathField(allow_folders=True, blank=True, max_length=255, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github/ExosetProd'),
        ),
    ]
