# Generated by Django 4.2.11 on 2024-05-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20220411_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_path_statement', models.CharField(blank=True, max_length=455, null=True)),
                ('html_path_solution', models.CharField(blank=True, max_length=455, null=True)),
                ('style', models.FilePathField(blank=True, max_length=455, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/accessibility_files/')),
                ('figures', models.FilePathField(allow_folders=True, blank=True, max_length=455, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/accessibility_files/figures/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.resource')),
            ],
        ),
    ]
