# Generated by Django 3.0.4 on 2021-03-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20210316_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FilePathField(path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/mediagithub')),
                ('style', models.FilePathField(blank=True, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/mediagithub')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.Resource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='resourcesourcefile',
            constraint=models.UniqueConstraint(fields=('source', 'style'), name='different_source_style'),
        ),
    ]
