# Generated by Django 3.0.4 on 2021-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20210316_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='source',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github'),
        ),
        migrations.AlterField(
            model_name='resourcesourcefile',
            name='style',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/github'),
        ),
    ]
