# Generated by Django 4.2.11 on 2024-09-23 12:53

from django.db import migrations, models
import django.db.models.deletion
import exoset.notebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('FRANÇAIS', 'Français'), ('ENGLISH', 'English')], default='FRANÇAIS', max_length=8)),
                ('course', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('repository', models.URLField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.CharField(blank=True, max_length=1500)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('local_path', models.FilePathField(path='/home/maria/Documents/epfl/notebooks/notebooks_test')),
            ],
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('FRANÇAIS', 'Français'), ('ENGLISH', 'English')], default='FRANÇAIS', max_length=8)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.CharField(blank=True, max_length=1500)),
                ('type', models.CharField(max_length=255)),
                ('html_view', models.FileField(blank=True, storage=exoset.notebook.models.OverwriteStorage, upload_to=exoset.notebook.models.git_repository_directory_path)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('git_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.gitrepository')),
            ],
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='kernel',
            field=models.ManyToManyField(blank=True, related_name='kernel', to='notebook.kernel'),
        ),
    ]
