# Generated by Django 4.2.11 on 2024-09-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='type',
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='local_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=255, path='/home/maria/Documents/epfl/exoset_project/exoset/exoset/exoset/media/notebooks/'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebook.nbtype'),
        ),
    ]
