# Generated by Django 4.2.11 on 2024-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_nbtype_remove_notebook_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='last_commit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
