# Generated by Django 4.2.11 on 2024-10-03 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_gitrepository_last_commit_notebook_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagConceptNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('concept_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='language',
            field=models.CharField(choices=[('Français', 'Français'), ('English', 'English')], default='Français', max_length=8),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='language',
            field=models.CharField(choices=[('Français', 'Français'), ('English', 'English')], default='Français', max_length=8),
        ),
        migrations.CreateModel(
            name='TagConceptNotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebook')),
                ('tag_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.tagconceptnotebook')),
            ],
        ),
    ]
