# Generated by Django 3.0.4 on 2021-04-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('MAT', 'Mathematics'), ('PHY', 'Physics'), ('CHE', 'Chemistry')], default='MAT', max_length=3)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssignPrerequisiteResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ManyToManyField(to='prerequisite.Prerequisite')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Resource')),
            ],
        ),
    ]
