# Generated by Django 3.0.12 on 2021-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('official', models.BooleanField(default=False)),
            ],
        ),
    ]
